### ISSUE TITLE
Improvments

### ISSUE THREAD

**Issue by waradu** [emmoghimi/vue-iconsax#3]
- Ability Change Stroke Width
- Fix "Browse Icons" Link access (can't access it)
- Make it so it can be used in Nuxt for example without importing it or just adding it to components in nuxt.config (idk if already possible)

**Comment by JaxThePrime** [comment]
@Waradu 
Hello my friend first two items are fixed available now but i didn't understand the last one.
Let me know if theres any problem configing in nuxt but i have tried it myself and it worked fine and you dont need to set anything in the nuxt.confi.ts, just  import and use like the descriptions and examples on the repo and npm
